# Generated by Django 4.1 on 2022-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('facebookLK', models.URLField(blank=True, max_length=255, null=True)),
                ('twitterLK', models.URLField(blank=True, max_length=255, null=True)),
                ('googlePlusLK', models.URLField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
