# Generated by Django 4.1 on 2022-08-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='picture',
            new_name='img',
        ),
    ]
