# Generated by Django 4.1 on 2022-08-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='img',
        ),
    ]
